/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWorkVideosRouteImport } from './routes/_app.work-videos'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppUploadLeadsRouteImport } from './routes/_app.upload-leads'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppStatusMarketingRouteImport } from './routes/_app.status-marketing'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRewardsRouteImport } from './routes/_app.rewards'
import { Route as AppReportsHrRouteImport } from './routes/_app.reports-hr'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPaidLeadsRouteImport } from './routes/_app.paid-leads'
import { Route as AppLogoutRouteImport } from './routes/_app.logout'
import { Route as AppLegalDocumentsRouteImport } from './routes/_app.legal-documents'
import { Route as AppLeadsTomorrowRouteImport } from './routes/_app.leads-tomorrow'
import { Route as AppLeadsTodayRouteImport } from './routes/_app.leads-today'
import { Route as AppLeadsPreviousRouteImport } from './routes/_app.leads-previous'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppImportantLinksRouteImport } from './routes/_app.important-links'
import { Route as AppHrManagementRouteImport } from './routes/_app.hr-management'
import { Route as AppHowToUseRouteImport } from './routes/_app.how-to-use'
import { Route as AppCreditCardReferRouteImport } from './routes/_app.credit-card-refer'
import { Route as AppBrokerReportsRouteImport } from './routes/_app.broker-reports'
import { Route as AppBrokerLegalityRouteImport } from './routes/_app.broker-legality'
import { Route as AppBroadcastRouteImport } from './routes/_app.broadcast'
import { Route as AppBankAccountReferRouteImport } from './routes/_app.bank-account-refer'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAdminIncomeRouteImport } from './routes/_app.admin-income'
import { Route as AppActivityLogsRouteImport } from './routes/_app.activity-logs'
import { Route as AppAccountsPendingRouteImport } from './routes/_app.accounts-pending'
import { Route as AppAccountsOpenRouteImport } from './routes/_app.accounts-open'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkVideosRoute = AppWorkVideosRouteImport.update({
  id: '/work-videos',
  path: '/work-videos',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadLeadsRoute = AppUploadLeadsRouteImport.update({
  id: '/upload-leads',
  path: '/upload-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusMarketingRoute = AppStatusMarketingRouteImport.update({
  id: '/status-marketing',
  path: '/status-marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsHrRoute = AppReportsHrRouteImport.update({
  id: '/reports-hr',
  path: '/reports-hr',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaidLeadsRoute = AppPaidLeadsRouteImport.update({
  id: '/paid-leads',
  path: '/paid-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLogoutRoute = AppLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalDocumentsRoute = AppLegalDocumentsRouteImport.update({
  id: '/legal-documents',
  path: '/legal-documents',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsTomorrowRoute = AppLeadsTomorrowRouteImport.update({
  id: '/leads-tomorrow',
  path: '/leads-tomorrow',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsTodayRoute = AppLeadsTodayRouteImport.update({
  id: '/leads-today',
  path: '/leads-today',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsPreviousRoute = AppLeadsPreviousRouteImport.update({
  id: '/leads-previous',
  path: '/leads-previous',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppImportantLinksRoute = AppImportantLinksRouteImport.update({
  id: '/important-links',
  path: '/important-links',
  getParentRoute: () => AppRoute,
} as any)
const AppHrManagementRoute = AppHrManagementRouteImport.update({
  id: '/hr-management',
  path: '/hr-management',
  getParentRoute: () => AppRoute,
} as any)
const AppHowToUseRoute = AppHowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditCardReferRoute = AppCreditCardReferRouteImport.update({
  id: '/credit-card-refer',
  path: '/credit-card-refer',
  getParentRoute: () => AppRoute,
} as any)
const AppBrokerReportsRoute = AppBrokerReportsRouteImport.update({
  id: '/broker-reports',
  path: '/broker-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppBrokerLegalityRoute = AppBrokerLegalityRouteImport.update({
  id: '/broker-legality',
  path: '/broker-legality',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppBankAccountReferRoute = AppBankAccountReferRouteImport.update({
  id: '/bank-account-refer',
  path: '/bank-account-refer',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIncomeRoute = AppAdminIncomeRouteImport.update({
  id: '/admin-income',
  path: '/admin-income',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityLogsRoute = AppActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsPendingRoute = AppAccountsPendingRouteImport.update({
  id: '/accounts-pending',
  path: '/accounts-pending',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsOpenRoute = AppAccountsOpenRouteImport.update({
  id: '/accounts-open',
  path: '/accounts-open',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts-open': typeof AppAccountsOpenRoute
  '/accounts-pending': typeof AppAccountsPendingRoute
  '/activity-logs': typeof AppActivityLogsRoute
  '/admin-income': typeof AppAdminIncomeRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/bank-account-refer': typeof AppBankAccountReferRoute
  '/broadcast': typeof AppBroadcastRoute
  '/broker-legality': typeof AppBrokerLegalityRoute
  '/broker-reports': typeof AppBrokerReportsRoute
  '/credit-card-refer': typeof AppCreditCardReferRoute
  '/how-to-use': typeof AppHowToUseRoute
  '/hr-management': typeof AppHrManagementRoute
  '/important-links': typeof AppImportantLinksRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads-previous': typeof AppLeadsPreviousRoute
  '/leads-today': typeof AppLeadsTodayRoute
  '/leads-tomorrow': typeof AppLeadsTomorrowRoute
  '/legal-documents': typeof AppLegalDocumentsRoute
  '/logout': typeof AppLogoutRoute
  '/paid-leads': typeof AppPaidLeadsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/reports-hr': typeof AppReportsHrRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/status-marketing': typeof AppStatusMarketingRoute
  '/support': typeof AppSupportRoute
  '/upload-leads': typeof AppUploadLeadsRoute
  '/wallet': typeof AppWalletRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/work-videos': typeof AppWorkVideosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts-open': typeof AppAccountsOpenRoute
  '/accounts-pending': typeof AppAccountsPendingRoute
  '/activity-logs': typeof AppActivityLogsRoute
  '/admin-income': typeof AppAdminIncomeRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/bank-account-refer': typeof AppBankAccountReferRoute
  '/broadcast': typeof AppBroadcastRoute
  '/broker-legality': typeof AppBrokerLegalityRoute
  '/broker-reports': typeof AppBrokerReportsRoute
  '/credit-card-refer': typeof AppCreditCardReferRoute
  '/how-to-use': typeof AppHowToUseRoute
  '/hr-management': typeof AppHrManagementRoute
  '/important-links': typeof AppImportantLinksRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/leads-previous': typeof AppLeadsPreviousRoute
  '/leads-today': typeof AppLeadsTodayRoute
  '/leads-tomorrow': typeof AppLeadsTomorrowRoute
  '/legal-documents': typeof AppLegalDocumentsRoute
  '/logout': typeof AppLogoutRoute
  '/paid-leads': typeof AppPaidLeadsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/reports-hr': typeof AppReportsHrRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/status-marketing': typeof AppStatusMarketingRoute
  '/support': typeof AppSupportRoute
  '/upload-leads': typeof AppUploadLeadsRoute
  '/wallet': typeof AppWalletRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/work-videos': typeof AppWorkVideosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/accounts-open': typeof AppAccountsOpenRoute
  '/_app/accounts-pending': typeof AppAccountsPendingRoute
  '/_app/activity-logs': typeof AppActivityLogsRoute
  '/_app/admin-income': typeof AppAdminIncomeRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/bank-account-refer': typeof AppBankAccountReferRoute
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/broker-legality': typeof AppBrokerLegalityRoute
  '/_app/broker-reports': typeof AppBrokerReportsRoute
  '/_app/credit-card-refer': typeof AppCreditCardReferRoute
  '/_app/how-to-use': typeof AppHowToUseRoute
  '/_app/hr-management': typeof AppHrManagementRoute
  '/_app/important-links': typeof AppImportantLinksRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/leads-previous': typeof AppLeadsPreviousRoute
  '/_app/leads-today': typeof AppLeadsTodayRoute
  '/_app/leads-tomorrow': typeof AppLeadsTomorrowRoute
  '/_app/legal-documents': typeof AppLegalDocumentsRoute
  '/_app/logout': typeof AppLogoutRoute
  '/_app/paid-leads': typeof AppPaidLeadsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/reports-hr': typeof AppReportsHrRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/status-marketing': typeof AppStatusMarketingRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/upload-leads': typeof AppUploadLeadsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/work-videos': typeof AppWorkVideosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending'
    | '/reset-password'
    | '/sitemap.xml'
    | '/accounts-open'
    | '/accounts-pending'
    | '/activity-logs'
    | '/admin-income'
    | '/announcements'
    | '/attendance'
    | '/bank-account-refer'
    | '/broadcast'
    | '/broker-legality'
    | '/broker-reports'
    | '/credit-card-refer'
    | '/how-to-use'
    | '/hr-management'
    | '/important-links'
    | '/leaderboard'
    | '/leads-previous'
    | '/leads-today'
    | '/leads-tomorrow'
    | '/legal-documents'
    | '/logout'
    | '/paid-leads'
    | '/profile'
    | '/reports'
    | '/reports-hr'
    | '/rewards'
    | '/settings'
    | '/status-marketing'
    | '/support'
    | '/upload-leads'
    | '/wallet'
    | '/whatsapp'
    | '/work-videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/pending'
    | '/reset-password'
    | '/sitemap.xml'
    | '/accounts-open'
    | '/accounts-pending'
    | '/activity-logs'
    | '/admin-income'
    | '/announcements'
    | '/attendance'
    | '/bank-account-refer'
    | '/broadcast'
    | '/broker-legality'
    | '/broker-reports'
    | '/credit-card-refer'
    | '/how-to-use'
    | '/hr-management'
    | '/important-links'
    | '/leaderboard'
    | '/leads-previous'
    | '/leads-today'
    | '/leads-tomorrow'
    | '/legal-documents'
    | '/logout'
    | '/paid-leads'
    | '/profile'
    | '/reports'
    | '/reports-hr'
    | '/rewards'
    | '/settings'
    | '/status-marketing'
    | '/support'
    | '/upload-leads'
    | '/wallet'
    | '/whatsapp'
    | '/work-videos'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/pending'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_app/accounts-open'
    | '/_app/accounts-pending'
    | '/_app/activity-logs'
    | '/_app/admin-income'
    | '/_app/announcements'
    | '/_app/attendance'
    | '/_app/bank-account-refer'
    | '/_app/broadcast'
    | '/_app/broker-legality'
    | '/_app/broker-reports'
    | '/_app/credit-card-refer'
    | '/_app/how-to-use'
    | '/_app/hr-management'
    | '/_app/important-links'
    | '/_app/leaderboard'
    | '/_app/leads-previous'
    | '/_app/leads-today'
    | '/_app/leads-tomorrow'
    | '/_app/legal-documents'
    | '/_app/logout'
    | '/_app/paid-leads'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/reports-hr'
    | '/_app/rewards'
    | '/_app/settings'
    | '/_app/status-marketing'
    | '/_app/support'
    | '/_app/upload-leads'
    | '/_app/wallet'
    | '/_app/whatsapp'
    | '/_app/work-videos'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-videos': {
      id: '/_app/work-videos'
      path: '/work-videos'
      fullPath: '/work-videos'
      preLoaderRoute: typeof AppWorkVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload-leads': {
      id: '/_app/upload-leads'
      path: '/upload-leads'
      fullPath: '/upload-leads'
      preLoaderRoute: typeof AppUploadLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status-marketing': {
      id: '/_app/status-marketing'
      path: '/status-marketing'
      fullPath: '/status-marketing'
      preLoaderRoute: typeof AppStatusMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports-hr': {
      id: '/_app/reports-hr'
      path: '/reports-hr'
      fullPath: '/reports-hr'
      preLoaderRoute: typeof AppReportsHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paid-leads': {
      id: '/_app/paid-leads'
      path: '/paid-leads'
      fullPath: '/paid-leads'
      preLoaderRoute: typeof AppPaidLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logout': {
      id: '/_app/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AppLogoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal-documents': {
      id: '/_app/legal-documents'
      path: '/legal-documents'
      fullPath: '/legal-documents'
      preLoaderRoute: typeof AppLegalDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-tomorrow': {
      id: '/_app/leads-tomorrow'
      path: '/leads-tomorrow'
      fullPath: '/leads-tomorrow'
      preLoaderRoute: typeof AppLeadsTomorrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-today': {
      id: '/_app/leads-today'
      path: '/leads-today'
      fullPath: '/leads-today'
      preLoaderRoute: typeof AppLeadsTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-previous': {
      id: '/_app/leads-previous'
      path: '/leads-previous'
      fullPath: '/leads-previous'
      preLoaderRoute: typeof AppLeadsPreviousRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/important-links': {
      id: '/_app/important-links'
      path: '/important-links'
      fullPath: '/important-links'
      preLoaderRoute: typeof AppImportantLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr-management': {
      id: '/_app/hr-management'
      path: '/hr-management'
      fullPath: '/hr-management'
      preLoaderRoute: typeof AppHrManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/how-to-use': {
      id: '/_app/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof AppHowToUseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit-card-refer': {
      id: '/_app/credit-card-refer'
      path: '/credit-card-refer'
      fullPath: '/credit-card-refer'
      preLoaderRoute: typeof AppCreditCardReferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broker-reports': {
      id: '/_app/broker-reports'
      path: '/broker-reports'
      fullPath: '/broker-reports'
      preLoaderRoute: typeof AppBrokerReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broker-legality': {
      id: '/_app/broker-legality'
      path: '/broker-legality'
      fullPath: '/broker-legality'
      preLoaderRoute: typeof AppBrokerLegalityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank-account-refer': {
      id: '/_app/bank-account-refer'
      path: '/bank-account-refer'
      fullPath: '/bank-account-refer'
      preLoaderRoute: typeof AppBankAccountReferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-income': {
      id: '/_app/admin-income'
      path: '/admin-income'
      fullPath: '/admin-income'
      preLoaderRoute: typeof AppAdminIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity-logs': {
      id: '/_app/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AppActivityLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts-pending': {
      id: '/_app/accounts-pending'
      path: '/accounts-pending'
      fullPath: '/accounts-pending'
      preLoaderRoute: typeof AppAccountsPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts-open': {
      id: '/_app/accounts-open'
      path: '/accounts-open'
      fullPath: '/accounts-open'
      preLoaderRoute: typeof AppAccountsOpenRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsOpenRoute: typeof AppAccountsOpenRoute
  AppAccountsPendingRoute: typeof AppAccountsPendingRoute
  AppActivityLogsRoute: typeof AppActivityLogsRoute
  AppAdminIncomeRoute: typeof AppAdminIncomeRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBankAccountReferRoute: typeof AppBankAccountReferRoute
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppBrokerLegalityRoute: typeof AppBrokerLegalityRoute
  AppBrokerReportsRoute: typeof AppBrokerReportsRoute
  AppCreditCardReferRoute: typeof AppCreditCardReferRoute
  AppHowToUseRoute: typeof AppHowToUseRoute
  AppHrManagementRoute: typeof AppHrManagementRoute
  AppImportantLinksRoute: typeof AppImportantLinksRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLeadsPreviousRoute: typeof AppLeadsPreviousRoute
  AppLeadsTodayRoute: typeof AppLeadsTodayRoute
  AppLeadsTomorrowRoute: typeof AppLeadsTomorrowRoute
  AppLegalDocumentsRoute: typeof AppLegalDocumentsRoute
  AppLogoutRoute: typeof AppLogoutRoute
  AppPaidLeadsRoute: typeof AppPaidLeadsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReportsHrRoute: typeof AppReportsHrRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatusMarketingRoute: typeof AppStatusMarketingRoute
  AppSupportRoute: typeof AppSupportRoute
  AppUploadLeadsRoute: typeof AppUploadLeadsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppWorkVideosRoute: typeof AppWorkVideosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsOpenRoute: AppAccountsOpenRoute,
  AppAccountsPendingRoute: AppAccountsPendingRoute,
  AppActivityLogsRoute: AppActivityLogsRoute,
  AppAdminIncomeRoute: AppAdminIncomeRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBankAccountReferRoute: AppBankAccountReferRoute,
  AppBroadcastRoute: AppBroadcastRoute,
  AppBrokerLegalityRoute: AppBrokerLegalityRoute,
  AppBrokerReportsRoute: AppBrokerReportsRoute,
  AppCreditCardReferRoute: AppCreditCardReferRoute,
  AppHowToUseRoute: AppHowToUseRoute,
  AppHrManagementRoute: AppHrManagementRoute,
  AppImportantLinksRoute: AppImportantLinksRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLeadsPreviousRoute: AppLeadsPreviousRoute,
  AppLeadsTodayRoute: AppLeadsTodayRoute,
  AppLeadsTomorrowRoute: AppLeadsTomorrowRoute,
  AppLegalDocumentsRoute: AppLegalDocumentsRoute,
  AppLogoutRoute: AppLogoutRoute,
  AppPaidLeadsRoute: AppPaidLeadsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppReportsHrRoute: AppReportsHrRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatusMarketingRoute: AppStatusMarketingRoute,
  AppSupportRoute: AppSupportRoute,
  AppUploadLeadsRoute: AppUploadLeadsRoute,
  AppWalletRoute: AppWalletRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppWorkVideosRoute: AppWorkVideosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
